### ISSUE TITLE
./myyt: 9: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by StereoFox** [Bugswriter/myyt#2]
Hi Bugswriter, thanks for the script!

When running ./dmenyt or ./myyt it prompts for the search query. Regardless of what I enter I receive the syntax error

```
$ ./myyt
Search query: test
./myyt: 9: Syntax error: redirection unexpected
```

Dependencies:
```
fzf is already the newest version (0.20.0-1).
mpv is already the newest version (0.32.0-1ubuntu1).
suckless-tools is already the newest version (44-1). [This contains dmenu]
youtube-dl is already the newest version (2020.03.24-1).
```

API key is properly inserted as variable in terminal,
output of echo:
```
user@desktop$: echo $YT_API_KEY
AIzaSyB-rGfbeC2w8dMxxxxxxx
```

**Comment by slavistan** [comment]
The error is due to the usage of the here-string construct (`<<<`) in line 9: `query="$(sed 's/ /+/g' <<<$query)"`. Presumably @Bugswriter links */bin/sh* to bash whereas some people use a strictly POSIX compliant shell. Since the here-string is a bashism and not POSIX compliant this script will fail for the latter. 

To fix the issue either change the executing shell to `#!/bin/bash`, or pipe in the input using `query="$(echo "$query" | sed 's/ /+/g')"` or use the POSIX-compliant [heredoc](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07_04) construct:

```
query="$(sed 's/ /+/g' <<EOF
$query
EOF
)"
``` 

Herestring is simply syntactic sugar for single-line heredoc input.

**Comment by bugswriter** [comment]
So does this worked for you. Your error is fixed?

**Comment by bugswriter** [comment]
If you use telegram then you can contact me => @bugswriter  or join my
linux group @linuxindia (pretty cool)

**Comment by StereoFox** [comment]
That worked, thanks!
