### ISSUE TITLE
Script doesn't work outside the terminal

### ISSUE THREAD

**Issue by ghost** [Bugswriter/myyt#3]
I'll explain the title here. So when the script is invoked with the standard dmenu_run script, everything works fine but with my [dmenu script](http://ix.io/2JGo) which should basically work the same way as the former, I get this error from jq:
`jq: error (at <stdin>:14): can't iterate over null (null)`
How I found out about this bug is that if I run your two scripts in the terminal, it works as expected but when I put a key binding in the header file for dwm, I was getting empty prompts i.e. the search results weren't being displayed. And apparently that was happening because of the fq error.
The only workaround I have right now is to invoke the standard dmenu_run script, type your script's name and do the search from there.
Since this is a new project, the issues are expected. However, your script is very helpful. Thanks.
Also, please check [this video.](https://user-images.githubusercontent.com/64492098/103164536-d856d280-4834-11eb-8808-614cd746efcc.mp4)
All the requirements are fulfilled.

**Comment by bugswriter** [comment]
I will not recommend using dmenu_run script or do any kind of change in dmenu run. What shell are you using? try to run dmenyt from terminal .. I echo the search query on terminal on line 10 in my dmenyt. 
I guess the main command have no issue it's just your dmenu is not reading input properly. 
tell me if you are able to fix this.

also check this -> https://www.reddit.com/r/linux/comments/kl8ig3/commandline_youtube_video_search_and_play_utility/
it's same program but without API. it's web scraping. You can try this. But since it's web scraping it's not very stable.
If you don't exceed you daily limit quota ..you can continue with my script. Bind it to some key.

**Comment by bugswriter** [comment]
Also this is not a project. It's just a bash script. But I think I can do this! thanks for the idea.

**Comment by ghost** [comment]
Hey so i don't know what happened but the script works all of a sudden. I had binded it to a key, and now that works too. Thanks for your time.
